name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Chạy khi push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Máy ảo chạy workflow
    steps:
      - uses: actions/checkout@v3  # Lấy code từ repo
        name: Checkout code

      - name: Set up Docker Buildx  # Cài công cụ build Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry  # Đăng nhập ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Tên GitHub của bạn
          password: ${{ secrets.GITHUB_TOKEN }}  # Token tự động từ GitHub

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/open-webui:latest .
          docker push ghcr.io/${{ github.repository_owner }}/open-webui:latest
